### ISSUE TITLE
Suggestion: Request for docs english version

### ISSUE THREAD

**Issue by karlpatrickespiritu** [zgldh/vuejs-laravel#3]

**Comment by zgldh** [comment]
Hi buddy, I'm still learning VueJS 2, so this lib wont be updated until I get there.
You can checked the latest Laravel 5.3 with VueJS 1.0. That's the official support to combine Laravel with VueJS.
Thank you for your attention.

**Comment by karlpatrickespiritu** [comment]
Got it @zgldh. Thanks. Yeah, seems that laravel doesn't quite have support for SPA apps using Vue atm. But I got mine working using [this one](https://github.com/dolbex/webpack-laravel). Will be waiting for your awesome stuff. Thanks!
